// <auto-generated />
namespace HubSpace.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.6.0-preview1-final")]
    public sealed partial class InicialSincronizacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicialSincronizacao));
        
        string IMigrationMetadata.Id
        {
            get { return "202607181730250_InicialSincronizacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
